### 1. Qu'est-ce que NumPy ? Comment l'installer ?
Numpy est une bibliothèque du langage Python destinée à la manipulation de tableau multidimentionnels

### 2. Qu'est-ce qu'un tableau (array) et en quoi diffère-t-il d'une liste ? Quel est le nom de la classe de tableau intégrée dans NumPy ?
Un tableau est un regroupement de données de même type.

La différence entre un tableau et une liste est qu'une liste peut comporter des éléments de types différents alors qu'un tableau ne peut contenir que des éléments de même type.

### 3. Créez les tableaux NumPy

#### a. Un tableau 1-D appelé "zeros" ayant 10 éléments, tous les éléments étant définis à zéro.

In [33]:
import numpy as np

zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### b. Un tableau 1-D appelé "vowels" ayant les éléments 'a', 'e', 'i', 'o' et 'u'.

In [34]:
import numpy as np

vowels = np.array(['a', 'e', 'i', 'o', 'u'])
print(vowels)

['a' 'e' 'i' 'o' 'u']


#### c. Un tableau 2-D appelé "ones" ayant 2 lignes et 5 colonnes, tous les éléments étant définis à 1 et le type de données (dtype) en int.


In [35]:
import numpy as np

ones = np.ones((2, 5), dtype=int)
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]]


#### d. Utilisez des listes Python imbriquées pour créer un tableau 2-D appelé "myarray1" ayant 3 lignes et 3 colonnes et stockez les données suivantes : 2.7, -2, -19 ; 0, 3.4, 99.9 ; 10.6, 0, 13


In [36]:

myarray1 = [
    [2.7, -2, -19],
    [0, 3.4, 99.9],
    [10.6, 0, 13]
]

print(myarray1)

[[2.7, -2, -19], [0, 3.4, 99.9], [10.6, 0, 13]]


#### e. Un tableau 2-D appelé "myarray2" en utilisant arange() ayant 3 lignes et 5 colonnes avec une valeur de départ de 4, un pas de 4 et le type de données en float

In [37]:
import numpy as np

myarray2 = np.arange(4, 64, 4, dtype=float).reshape((3, 5))
print(myarray2)

[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


### 4. À l'aide des tableaux créés dans la question 3 ci-dessus, écrivez des commandes NumPy pour ce qui suit :

#### a. Trouver les dimensions, la forme, la taille, le type de données des éléments et la taille des éléments des tableaux "zeros", "vowels", "ones", "myarray1" et "myarray2".

In [38]:
print("zeros:")
print("Dimensions:", zeros.ndim)
print("Forme:", zeros.shape)
print("Taille:", zeros.size)
print("Type:", zeros.dtype)
print("Taille:", zeros.itemsize)

print("\nvowels:")
print("Dimensions:", vowels.ndim)
print("Forme:", vowels.shape)
print("Taille:", vowels.size)
print("Type:", vowels.dtype)
print("Taille:", vowels.itemsize)

print("\nones:")
print("Dimensions:", ones.ndim)
print("Forme:", ones.shape)
print("Taille:", ones.size)
print("Type:", ones.dtype)
print("Taille:", ones.itemsize)

print("\nmyarray1:")
myarray1 = np.array(myarray1)
print("Dimensions:", myarray1.ndim)
print("Forme:", myarray1.shape)
print("Taille:", myarray1.size)
print("Type:", myarray1.dtype)
print("Taille:", myarray1.itemsize)

print("\nmyarray2:")
print("Dimensions:", myarray2.ndim)
print("Forme:", myarray2.shape)
print("Taille:", myarray2.size)
print("Type:", myarray2.dtype)
print("Taille:", myarray2.itemsize)

zeros:
Dimensions: 1
Forme: (10,)
Taille: 10
Type: float64
Taille: 8

vowels:
Dimensions: 1
Forme: (5,)
Taille: 5
Type: <U1
Taille: 4

ones:
Dimensions: 2
Forme: (2, 5)
Taille: 10
Type: int32
Taille: 4

myarray1:
Dimensions: 2
Forme: (3, 3)
Taille: 9
Type: float64
Taille: 8

myarray2:
Dimensions: 2
Forme: (3, 5)
Taille: 15
Type: float64
Taille: 8


#### b. Remodeler le tableau "ones" pour avoir les 10 éléments dans une seule ligne.

In [39]:
ones = ones.reshape(1, 10)
print(ones)

[[1 1 1 1 1 1 1 1 1 1]]


#### c. Afficher le 2e et le 3e élément du tableau "vowels".

In [40]:
print("2eme élément :", vowels[1])
print("3eme élément :", vowels[2])

2eme élément : e
3eme élément : i


#### d. Afficher tous les éléments de la 2e et 3e ligne du tableau "myarray1"

In [41]:
print("2eme ligne :", myarray1[1, :])
print("3eme ligne :", myarray1[2, :])

2eme ligne : [ 0.   3.4 99.9]
3eme ligne : [10.6  0.  13. ]


#### e. Afficher les éléments de la 1re et 2e colonne du tableau "myarray1".

In [42]:
print("1ere colonne :", myarray1[:, 0])
print("2eme colonne :", myarray1[:, 1])

1ere colonne : [ 2.7  0.  10.6]
2eme colonne : [-2.   3.4  0. ]


#### f. Afficher les éléments de la 1re colonne de la 2e et 3e ligne du tableau "myarray1".

In [43]:
print("1ere colonne :", myarray1[:, 0])
print("2eme ligne :", myarray1[:, 1])
print("3eme ligne :", myarray1[:, 2])

1ere colonne : [ 2.7  0.  10.6]
2eme ligne : [-2.   3.4  0. ]
3eme ligne : [-19.   99.9  13. ]


#### g. Inverser le tableau des "vowels".

In [44]:
vowels = vowels[::-1]
print(vowels)

['u' 'o' 'i' 'e' 'a']


### 5. À l'aide des tableaux créés dans la question 4 ci-dessus, écrivez des commandes NumPy pour ce qui suit :

#### a. Diviser tous les éléments du tableau "ones" par 3.

In [45]:
result = ones / 3
print(result)

[[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333 0.33333333
  0.33333333 0.33333333 0.33333333 0.33333333]]


#### b. Additionner les tableaux "myarray1" et "myarray2".

In [46]:
myarray2 = np.arange(4, 39, 4).reshape((3, 3))
result = myarray1 + myarray2
print(result)

[[  6.7   6.   -7. ]
 [ 16.   23.4 123.9]
 [ 38.6  32.   49. ]]


#### c. Soustraire "myarray1" de "myarray2" et stocker le résultat dans un nouveau tableau.

In [47]:
result = myarray2 - myarray1

print(result)

[[  1.3  10.   31. ]
 [ 16.   16.6 -75.9]
 [ 17.4  32.   23. ]]


#### d. Multiplier élément par élément "myarray1" et "myarray2".

In [48]:
result = myarray2 * myarray1

print(result)

[[  10.8  -16.  -228. ]
 [   0.    68.  2397.6]
 [ 296.8    0.   468. ]]


#### e. Effectuer la multiplication matricielle de "myarray1" et "myarray2" et stocker le résultat dans un nouveau tableau "myarray3".

In [49]:
myarray3 = np.dot(myarray1, myarray2)  # ou myarray1 @ myarray2
print(myarray3)

[[-553.2 -626.4 -699.6]
 [2851.6 3264.8 3678. ]
 [ 406.4  500.8  595.2]]


#### f. Diviser "myarray1" par "myarray2".

In [50]:
result = myarray1 / myarray2
print(result)

[[ 0.675      -0.25       -1.58333333]
 [ 0.          0.17        4.1625    ]
 [ 0.37857143  0.          0.36111111]]


#### g. Trouver le cube de tous les éléments de "myarray1" et diviser le tableau résultant par 2.

In [51]:
result = (myarray1 ** 3) / 2
print(result)

[[ 9.841500e+00 -4.000000e+00 -3.429500e+03]
 [ 0.000000e+00  1.965200e+01  4.985015e+05]
 [ 5.955080e+02  0.000000e+00  1.098500e+03]]


#### h. Trouver la racine carrée de tous les éléments de "myarray2" et diviser le tableau résultant par 2. Le résultat doit être arrondi à deux décimales.

In [52]:
result = np.round(np.sqrt(myarray2) / 2, decimals=2)
print(result)

[[1.   1.41 1.73]
 [2.   2.24 2.45]
 [2.65 2.83 3.  ]]


### 6. À l'aide des tableaux créés dans la question 3 ci-dessus, écrivez des commandes NumPy pour ce qui suit :

#### a. Trouver la transposée de "ones" et "myarray2".

In [53]:
transposee_ones = np.transpose(ones)
transposee_myarray2 = np.transpose(myarray2)
print("transposée ones :", transposee_ones)
print("transposée myarray2 :", transposee_myarray2)

transposée ones : [[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]
transposée myarray2 : [[ 4 16 28]
 [ 8 20 32]
 [12 24 36]]


#### b. Trier le tableau "vowels" en ordre inverse.

In [54]:
ordre_inverse_trie = np.sort(vowels, kind='mergesort')[::-1]
print(ordre_inverse_trie)

['u' 'o' 'i' 'e' 'a']


#### c. Trier le tableau "myarray1" de manière à placer la plus petite valeur de la colonne dans la première ligne, et ainsi de suite.

In [55]:
tri_indices = np.argsort(myarray1, axis=0)
myarray1_trie = myarray1[tri_indices, np.arange(myarray1.shape[1])]
print(myarray1_trie)

[[  0.   -2.  -19. ]
 [  2.7   0.   13. ]
 [ 10.6   3.4  99.9]]


### 7. À l'aide des tableaux créés dans la question 4 ci-dessus, écrivez des commandes NumPy pour ce qui suit :

#### a. Utilisez numpy.split() pour diviser le tableau "myarray2" en 5 tableaux. Stockez vos tableaux résultants dans "myarray2A", "myarray2B", "myarray2C", "myarray2D" et "myarray2E". Imprimez les tableaux "myarray2A", "myarray2B", "myarray2C", "myarray2D" et "myarray2E".

In [56]:
myarray2 = np.arange(4, 64, 4, dtype=float).reshape((5, 3))
myarray2A, myarray2B, myarray2C, myarray2D, myarray2E = np.split(myarray2, 5)
print("myarray2A :")
print(myarray2A)
print("\nmyarray2B :")
print(myarray2B)
print("\nmyarray2C :")
print(myarray2C)
print("\nmyarray2D :")
print(myarray2D)
print("\nmyarray2E :")
print(myarray2E)

myarray2A :
[[ 4.  8. 12.]]

myarray2B :
[[16. 20. 24.]]

myarray2C :
[[28. 32. 36.]]

myarray2D :
[[40. 44. 48.]]

myarray2E :
[[52. 56. 60.]]


#### b. Divisez le tableau "zeros" aux indices 2, 5, 7, 8 et stockez les tableaux résultants dans "zerosA", "zerosB", "zerosC" et "zerosD". Imprimez-les.

In [57]:
indices = [2, 5, 7, 8]
zerosA, zerosB, zerosC, zerosD = np.split(zeros, indices)[1::]

print("zerosA :", zerosA)
print("zerosB :", zerosB)
print("zerosC :", zerosC)
print("zerosD :", zerosD)

zerosA : [0. 0. 0.]
zerosB : [0. 0.]
zerosC : [0.]
zerosD : [0. 0.]


#### c. Concaténer les tableaux "myarray2A", "myarray2B" et "myarray2C" en un tableau ayant 3 lignes et 3 colonnes.

In [58]:
result = np.concatenate((myarray2A, myarray2B, myarray2C))
print(result)

[[ 4.  8. 12.]
 [16. 20. 24.]
 [28. 32. 36.]]


### 8. Créez un tableau 2-D appelé "myarray4" en utilisant arange() ayant 14 lignes et 3 colonnes avec une valeur de départ de -1, un pas de 0.25. Divisez ce tableau en 3 parties égales et imprimez le résultat.

In [59]:
myarray4 = np.arange(-1, 9.5, 0.25).reshape((14, 3))
result = np.array_split(myarray4, 3)

for i, part in enumerate(result, 1):
    print(f"{part}\n")

[[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]]

[[2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]
 [5.   5.25 5.5 ]
 [5.75 6.   6.25]]

[[6.5  6.75 7.  ]
 [7.25 7.5  7.75]
 [8.   8.25 8.5 ]
 [8.75 9.   9.25]]



### 9. À l'aide du "myarray4" créé dans les questions précédentes, écrivez des commandes pour ce qui suit :

#### a. Trouver la somme de tous les éléments.

In [60]:
result = np.sum(myarray4)
print(result)

173.25


#### b. Trouver la somme de tous les éléments par ligne.

In [61]:
result = np.sum(myarray4, axis=1)
print(result)

[-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]
